//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPersonel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int ID { get; set; }
        public string Ay { get; set; }
        public string Yil { get; set; }
        public Nullable<decimal> Elektrik { get; set; }
        public Nullable<decimal> Su { get; set; }
        public Nullable<decimal> DogalGaz { get; set; }
        public Nullable<decimal> Internet { get; set; }
        public Nullable<decimal> Maaslar { get; set; }
        public Nullable<decimal> Ekstra { get; set; }
        public string Notlar { get; set; }
    }
}
