//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPersonel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public short PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string TC { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<short> Rutbe { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual PersonelRutbe PersonelRutbe { get; set; }
    }
}
