//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPersonel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public Nullable<byte> UrunKategori { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<decimal> GelisFiyat { get; set; }
        public Nullable<decimal> SatisFiyat { get; set; }
        public string UrunDetay { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
